# Generated by Django 4.2.9 on 2024-01-30 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="课程名", max_length=20, unique=True, verbose_name="课程名"
                    ),
                ),
                (
                    "info",
                    models.TextField(blank=True, help_text="课程信息", verbose_name="信息"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="课程价格",
                        max_digits=6,
                        verbose_name="价格",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="课程讲师",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="讲师",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["-created_at"],
            },
        ),
    ]
