# Generated by Django 4.2.9 on 2024-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_course_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="课程名",
                max_length=20,
                unique=True,
                verbose_name="课程名",
            ),
        ),
    ]
