# Generated by Django 4.2.9 on 2024-01-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("bid", models.AutoField(primary_key=True, serialize=False)),
                ("isbn", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("pages", models.IntegerField()),
                ("price", models.FloatField(null=True)),
            ],
        ),
    ]
