# Generated by Django 4.2.9 on 2024-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_alter_books_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="price",
            field=models.FloatField(default=19.9, null=True),
        ),
    ]
